# 0.1 : shell for each command 
# 0.2 : shell keeps its settings
version: 0.2 

phases:
  install:
    commands:
      - echo INSTALL started on `date`
      - printenv
      - echo `pwd`
      - npm config set unsafe-perm=true
      - npm install bower -g
      - npm install grunt -g
      - sudo npm install
      - bower install --allow-root
      - echo INSTALL completed on `date`
  pre_build:
    commands:
      - echo PRE_BUILD started on `date`
      - echo `pwd`
      - bower -v
      - npm -v
      - grunt --force
      - echo PRE_BUILD completed on `date`
  build:
    commands:
      - echo BUILD started on `date`
      - df -h .; du -sh -- * | sort -hr
      - echo `pwd`
      - echo BUILD completed on `date`
  post_build:
    commands:      
      - echo POST_BUILD started on `date`
      - echo `pwd`
      - echo POST_BUILD completed on `date`
artifacts:
  files:
    - '**/*'
